# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_img',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
