# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_vc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trecord',
            name='no',
            field=models.CharField(db_column='r_no', max_length=12, primary_key=True, serialize=False, verbose_name='记录编号'),
        ),
        migrations.AlterField(
            model_name='trecord',
            name='punishment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='处罚方式'),
        ),
    ]
